// Código generado automáticamente. No editar.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "decoration7":return img`
....................
....................
....................
....................
....................
....................
.......22...22......
......2322.2222.....
......232222222.....
......222222222.....
.......22222b2......
........222b2.......
.........222........
..........2.........
....................
....................
....................
....................
....................
....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Código generado automáticamente. No editar.
